### ISSUE TITLE
yum-config-manager: command not found

### ISSUE THREAD

**Issue by cigamit** [rhtmgmtsa/SatelliteAutoInstaller#1]
./SatelliteDemoScript01092017.sh: line 300: yum-config-manager: command not found

I believe we need to move this check from line 91

`yum -q list installed yum-utils &>/dev/null && echo "yum-utils  is installed" || yum install -y yum-utils  --skip-broken`

down to around line 291

**Comment by ShaddGallegos** [comment]
if I do that then yum-config-manager commands dont work however I have cleaned a lot up sisnse this bug and added gnome-terminal for headless env
